export const dummyInstagramData = [
  {
    id: 1,
    username: "john_doe",
    avatar: "https://i.pravatar.cc/150?img=69",
    image: "https://picsum.photos/id/1015/600/400",
    likes: 123,
    caption: "Exploring beautiful places 🌍 #travel",
    comments: [
      {
        id: 101,
        username: "jane_smith",
        avatar: "https://i.pravatar.cc/150?img=2",
        comment: "Amazing view! 😍",
        timestamp: "2024-06-18T12:30:00Z",
      },
      {
        id: 102,
        username: "john_doe",
        avatar: "https://i.pravatar.cc/150?img=3",
        comment: "Looks like paradise! 🏝️",
        timestamp: "2024-06-18T13:15:00Z",
      },
      {
        id: 102,
        username: "john_doe",
        avatar: "https://i.pravatar.cc/150?img=3",
        comment:
          "Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️Looks like paradise! 🏝️",
        timestamp: "2024-06-18T13:15:00Z",
      },
    ],
    timestamp: "2024-06-18T10:00:00Z",
    location: "Santorini, Greece",
    tags: ["travel", "wanderlust", "nature"],
  },
  {
    id: 2,
    username: "sara_williams",
    avatar: "https://i.pravatar.cc/150?img=4",
    image: "https://picsum.photos/id/1020/600/400",
    likes: 456,
    caption: "Sunset vibes 🌅 #sunset",
    comments: [
      {
        id: 201,
        username: "mike_jones",
        avatar: "https://i.pravatar.cc/150?img=5",
        comment: "Beautiful colors! 🌈",
        timestamp: "2024-06-18T14:00:00Z",
      },
      {
        id: 202,
        username: "emily_green",
        avatar: "https://i.pravatar.cc/150?img=6",
        comment: "Gorgeous view! 😊",
        timestamp: "2024-06-18T14:30:00Z",
      },
    ],
    timestamp: "2024-06-17T18:45:00Z",
    location: "Malibu, California",
    tags: ["sunset", "sky", "nature"],
  },
  {
    id: 3,
    username: "david_clark",
    avatar: "https://i.pravatar.cc/150?img=7",
    image: "https://picsum.photos/id/1019/600/400",
    likes: 789,
    caption: "Good morning! ☀️ #morningvibes",
    comments: [
      {
        id: 301,
        username: "laura_brown",
        avatar: "https://i.pravatar.cc/150?img=8",
        comment: "Perfect way to start the day! 🌞",
        timestamp: "2024-06-17T08:30:00Z",
      },
      {
        id: 302,
        username: "alex_miller",
        avatar: "https://i.pravatar.cc/150?img=9",
        comment: "Love the sunlight! ✨",
        timestamp: "2024-06-17T09:00:00Z",
      },
    ],
    timestamp: "2024-06-17T07:15:00Z",
    location: "New York City, USA",
    tags: ["morning", "sunshine", "cityscape"],
  },
  {
    id: 4,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 5,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 6,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 7,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 8,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 9,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
  {
    id: 10,
    username: "julia_smith",
    avatar: "https://i.pravatar.cc/150?img=10",
    image: "https://picsum.photos/id/1018/600/400",
    likes: 234,
    caption: "Weekend getaway! 🏞️ #weekendvibes",
    comments: [
      {
        id: 401,
        username: "chris_walker",
        avatar: "https://i.pravatar.cc/150?img=11",
        comment: "Beautiful scenery! 🌲",
        timestamp: "2024-06-16T11:45:00Z",
      },
      {
        id: 402,
        username: "sophie_white",
        avatar: "https://i.pravatar.cc/150?img=12",
        comment: "Looks so peaceful! 😌",
        timestamp: "2024-06-16T12:30:00Z",
      },
    ],
    timestamp: "2024-06-16T10:00:00Z",
    location: "Yosemite National Park, USA",
    tags: ["nature", "getaway", "hiking"],
  },
];
